"""Update Report model to add state machine and aggregation fields

Revision ID: a7c8d94e5f6b
Revises: 5f8e63a4d1b2
Create Date: 2026-01-12 11:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = "a7c8d94e5f6b"
down_revision: str | Sequence[str] | None = "5f8e63a4d1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column with default value
    op.add_column(
        "report",
        sa.Column("status", sa.String(length=20), nullable=False, server_default="DRAFT"),
    )

    # Add timestamp columns
    op.add_column("report", sa.Column("submitted_at", sa.DateTime(), nullable=True))
    op.add_column("report", sa.Column("approved_at", sa.DateTime(), nullable=True))
    op.add_column("report", sa.Column("rejected_at", sa.DateTime(), nullable=True))
    op.add_column("report", sa.Column("rejection_reason", sa.Text(), nullable=True))

    # Add report summary/total columns
    op.add_column(
        "report", sa.Column("total_receipts", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "report", sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False, server_default="0.0")
    )
    op.add_column(
        "report", sa.Column("valid_receipts", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "report", sa.Column("invalid_receipts", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "report", sa.Column("warning_receipts", sa.Integer(), nullable=False, server_default="0")
    )

    # Add audit timestamp columns
    op.add_column("report", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.current_timestamp()))
    op.add_column(
        "report",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=func.current_timestamp(), onupdate=func.current_timestamp()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "updated_at")
    op.drop_column("report", "created_at")
    op.drop_column("report", "warning_receipts")
    op.drop_column("report", "invalid_receipts")
    op.drop_column("report", "valid_receipts")
    op.drop_column("report", "total_amount")
    op.drop_column("report", "total_receipts")
    op.drop_column("report", "rejection_reason")
    op.drop_column("report", "rejected_at")
    op.drop_column("report", "approved_at")
    op.drop_column("report", "submitted_at")
    op.drop_column("report", "status")
    # ### end Alembic commands ###
