import os
import random
from locust import HttpUser, task, between


class APIUser(HttpUser):
    wait_time = between(1, 2.5)
    host = os.getenv("TARGET_HOST", "http://localhost:8080")

    # Pre-generated JWT token for a test submitter
    # In a real scenario, this would be dynamically generated or fetched
    submitter_token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoidGVzdC1zdWJtaXR0ZXIiLCJyb2xlcyI6WyJzdWJtaXR0ZXIiXX0.some_submitter_jwt_signature"
    reviewer_token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoic2VyaWFsLWdhdGV3YXkiLCJyb2xlcyI6WyJyZXZpZXdlciJdfQ.some_reviewer_jwt_signature"

    def on_start(self):
        # Example: Create a report to get an ID for subsequent requests
        self.report_id = None
        response = self.client.post(
            "/v1/reports",
            headers={"Authorization": self.submitter_token},
            json={
                "title": "Performance Test Report",
                "description": "Generated by Locust",
            },
        )
        if response.status_code == 201:
            self.report_id = response.json().get("id")
            print(f"Created report {self.report_id} for performance test")
        else:
            print(f"Failed to create report: {response.status_code} - {response.text}")

    @task(3)  # Higher weight for creating receipts
    def create_receipt(self):
        if not self.report_id:
            return

        receipt_data = {
            "report_id": self.report_id,
            "user_id": "test-submitter",
            "file_name": f"receipt_{random.randint(1, 1000)}.jpg",
            "s3_object_key": f"receipts/test/receipt_{random.randint(1, 1000)}.jpg",
            "content_type": "image/jpeg",
            "notes": "Locust test receipt",
        }
        self.client.post(
            "/v1/receipts",
            headers={"Authorization": self.submitter_token},
            json=receipt_data,
            name="/v1/receipts [POST] - create",
        )

    @task(2)  # Medium weight for getting reports
    def get_reports(self):
        self.client.get(
            "/v1/reports",
            headers={"Authorization": self.submitter_token},
            name="/v1/reports [GET] - list",
        )

    @task(1)  # Lower weight for submitting/approving (less frequent)
    def submit_report(self):
        if self.report_id:
            self.client.post(
                f"/v1/reports/{self.report_id}/submit",
                headers={"Authorization": self.submitter_token},
                name="/v1/reports/{id}/submit [POST]",
            )
            # Simulate a reviewer looking at the inbox
            self.client.get(
                "/v1/review/inbox",
                headers={"Authorization": self.reviewer_token},
                name="/v1/review/inbox [GET]",
            )
            # Then approve
            self.client.post(
                f"/v1/reports/{self.report_id}/approve",
                headers={"Authorization": self.reviewer_token},
                json={"reviewer_notes": "Locust auto-approved"},
                name="/v1/reports/{id}/approve [POST]",
            )

    @task(1)  # Get health check frequently
    def health_check(self):
        self.client.get("/health", name="/health [GET]")
